apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sclti2r8u-go 
  janus-idp.io/tekton: sclti2r8u-go
  backstage.io/kubernetes-id: sclti2r8u-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sclti2r8u-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml