apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sclti2r8u-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:b3d5caf8268b1b5f22cba3056e46b9ec8ca0bcee@sha256:6579653f71932c58dd91f23a7cbd1242e0feaee779245b3dfdb837db5e21d21a
          name: container-image
